[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyspc"
version = "0.1.0"
description = "GRAMS SPC file reader for Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy"]

[tool.setuptools]
packages = ["pyspc"]

# Define Ruff to use 120 character line length
[tool.ruff]
line-length = 120