[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "spcfile"
version = "0.1.0"
description = "GRAMS SPC file reader for Python"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy"]

[project.optional-dependencies]
test = ["pytest"]

[tool.hatch.build.targets.wheel]
packages = ["spcfile"]

[tool.ruff]
line-length = 120
